##############################
#         CLIENTES           #
##############################

### Visualizar clientes registrados
GET http://localhost:3003/clientes

### Inserir Cliente
POST http://localhost:3003/clientes
Content-Type: application/json

{
    "cpf":  ,
    "nome_cliente": ""
}

### Atualizar/Alterar Cliente
PUT http://localhost:3003/clientes/7GreiHmz6RqbLzWTzGQS
Content-Type: application/json

{
    "cpf":  ,
    "nome_cliente": ""
}

### Excluir/apagar Cliente
DELETE http://localhost:3003/clientes/



##############################
#         PRODUTOS           #
##############################

### Visualizar Produtos registrados
GET http://localhost:3003/produtos

### Inserir Produto
POST http://localhost:3003/produtos
Content-Type: application/json

{
    "nome_produto": "",
    "preco": 
}

### Atualizar/alterar Produto
PUT http://localhost:3003/produtos/
Content-Type: application/json

{
    "nome_produto": "",
    "preco": 
}

### Excluir/apagar Produto
DELETE http://localhost:3003/produtos/
